### PR TITLE
URL updated. Piwik is now Matomo

### PR DESCRIPTION
**Pull request by kant**
Please, check this: https://matomo.org/blog/2018/01/piwik-is-now-matomo/. 
Plus minor fixes (proposals)

### CODE REVIEW

**Comment by mtub** [comment]
Please have a look, @marcbria. Again renaming the translation of plugin here…

**Comment by marcbria** [comment]
@kant proposal is over the **es_AR** version, not the **es_ES**.

"Complemento" is also a valid "plugin" translation, but so long ago (in the es_ES) we decided to translate "Plugins" as "Módulos". As far as he is working in the es_AR I have no recommendations.

About the "pikik -> matomo" renaming, @kant is right, but translation need to fits with the English version, so if English talks about piwik, I think we need to keep it in translations till original chain is changed.
 
As far as not everybody knows about it renaming my suggestion here is replacing the original English string as "Matomo (formerly known as piwik)" or something like this.

**Comment by mtub** [comment]
Any idea on how to proceed? Which Spanish version did you want to change, @kant ?

**Comment by mtub** [comment]
I would suggest to open an issue on GitHub regarding the Piwik name change - after it has been resolved for the English version, we can tackle translations.
https://github.com/pkp/pkp-lib/issues/

**Comment by marcbria** [comment]
Agree with @mtub.
The issue is global, so it need to be fixed up globally.

**Pull request closed without merging**
