### PR TITLE
GDPR revision

### PR DESCRIPTION
**Pull request by RBoelter**
## Revision of the plugin to make it GDPR-compliant and continue to use it within the EU.

New Feature(s):
- GDPR compliant tracking can be activated optionally
- selection between opt-in and opt-out tracking
- optional cookie-free use of Matomo
- customizable consent banner (position, content, buttons)
- german translation

ToDo:
- transform locale XML -> Po for OJS 3.2
- english translation should be reviewed
- translation of all other languages

@NateWr @asmecher

### CODE REVIEW

**Comment by NateWr** [comment]
Thanks @RBoelter! It looks like your code formatter has blown away every pre-existing line of code in the plugin, so it's very hard to evaluate what changes have been made to the code. In particular, we use tabs instead of spaces and reformatting as tabs will probably make the changes more clear.

Also, if you're able, could you rebase against our latest `master` branch to resolve the conflicts?

**Comment by RBoelter** [comment]
@NateWr I hope the rebase worked. I use PHPStorm and i think it uses spaces as default, i will change this for future developments.

**Comment by felixhelix** [comment]
Matomo supports cookie-less tracking which would make a user consent dispensible:

https://matomo.org/cookie-consent-banners/

The only thing needed - as far as I can see - is to add the line 

`_paq.push(['disableCookies']);`

below

`_paq.push(['trackPageView']);`

In the script generated.

This could also be optional for ojs installations that do not need to comply to GDPR.

@RBoelter

**Comment by RBoelter** [comment]
Sure, you can set `_paq.push(['disableCookies']);` to be more or less GDPR compliant. But this will only disable the cookie. What about the anonymization of IP addresses ([personal data](https://gdpr-info.eu/art-4-gdpr/))? If IP anonymization is enabled in the Matomo settings, then everything is ok. If not, the user should have the option to revoke the data collection.
I'm not a lawyer, but our data privacy supervisor considered the use of a consent banner as necessary, even though we use Matomo for all of our (cookie free) tracking.

And by the way, this pull request is more than two years old, I don't think it will be merged anymore.

**Comment by felixhelix** [comment]
@RBoelter thanks for your reply!

I thought I just continue the discussion here, instead of making it a new issue. But maybe I should, as there is also another thing I would like to see included: the exclusion of logged in admins and editors from tracking.
But how did you solve the issue for your journals? Did you develop a consent banner for OJS that you can share?

Yours

Felix

**Comment by RBoelter** [comment]
I'm not 100% sure, but as far as I remember, the plugin works only for the public-facing pages in OJS like the article landing pages, and doesn't track what happens on the admin/review/management pages. You should check this in your Matomo.
Excluding logged-in users completely from tracking could be a bit challenging.

Regarding the banner: This pull request contains a customizable consent banner, but I'm not sure if it still works after two years. We are currently using a different (custom) solution, but I'm not happy with that either, because we had to implement a feature to globally reject/accept tracking for all our services, and that doesn't work very well at the moment.

**Comment by felixhelix** [comment]
Thanks @RBoelter!

I make a feature request for including the cokie-less option. I think this should be no big thing to implement, and at least in our case seems to be sufficient.

Yours,

Felix

**Comment by felixhelix** [comment]
https://forum.pkp.sfu.ca/t/matomo-and-gdpr-apply-cookie-less-option/74227

**Comment by RBoelter** [comment]
If you need a quick solution, you can simply add your (cookie-less) Matomo code directly between `<head>...</head> `(`plugins/themes/<your theme>/templates/frontend/components/header.tpl`) of your theme. But this changes will be lost if you update your theme from the gallery.

**Pull request closed without merging**
